import fs from "node:fs"
import path from "node:path"
import { normalizePath, type Plugin, type ResolvedConfig } from "vite"

export type IntlMessagesDeclarationOptions = {
	/** JSON message files used to generate adjacent .d.json.ts declaration files. */
	messages: string | Array<string>
}

function resolveMessagesPaths(messages: string | Array<string>, config: ResolvedConfig) {
	return [messages].flat().map((msgPath) => {
		const fullPath = normalizePath(
			path.isAbsolute(msgPath) ? msgPath : path.resolve(config.root, msgPath)
		)
		if (!fs.existsSync(fullPath)) {
			throw new Error(
				`intlMessagesDeclaration points to a non-existent file: ${fullPath}`
			)
		}
		if (!fullPath.endsWith(".json")) {
			throw new Error(
				`intlMessagesDeclaration needs to point to a JSON file. Received: ${fullPath}`
			)
		}
		return fullPath
	})
}

function writeDeclaration(messagesPath: string) {
	const content = fs.readFileSync(messagesPath, "utf-8")
	const declarationPath = messagesPath.replace(/\.json$/, ".d.json.ts")
	const declaration = `// This file is auto-generated by intlMessagesDeclaration, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: ${content.trim()}
export default messages
`

	fs.writeFileSync(declarationPath, declaration)
}

function writeDeclarations(resolvedMessagesPaths: Array<string>) {
	for (const messagesPath of resolvedMessagesPaths) {
		writeDeclaration(messagesPath)
	}
}

export function intlMessagesDeclaration(options: IntlMessagesDeclarationOptions): Plugin {
	let config: ResolvedConfig
	let resolvedMessagesPaths: Array<string> = []

	return {
		name: "vite-use-intl-messages-declaration",
		configResolved(resolvedConfig) {
			config = resolvedConfig
			resolvedMessagesPaths = resolveMessagesPaths(options.messages, config)
			writeDeclarations(resolvedMessagesPaths)
		},
		configureServer(server) {
			server.watcher.add(resolvedMessagesPaths)
			server.watcher.on("change", (changedPath) => {
				if (resolvedMessagesPaths.includes(normalizePath(changedPath))) {
					writeDeclaration(normalizePath(changedPath))
				}
			})
		},
		buildStart() {
			writeDeclarations(resolvedMessagesPaths)
		},
	}
}

export default intlMessagesDeclaration
